version: "3.7"
services:
  bridges-express:
    container_name: bridges-express
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - 1337:1337
